services:
  backend:
    build:
      context: ./backend/app
    ports:
      - "5000:5000"
    volumes:
      - ./backend/app/static/audio:/app/static/audio
      - ./backend/app/static/assets:/app/static/assets
    restart: always
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TDA_FILE_PATH=${TDA_FILE_PATH}
      - GENERAL_PROCEDURES_FILE_PATH=${GENERAL_PROCEDURES_FILE_PATH}
      - GENERAL_RULES_FILE_PATH=${GENERAL_RULES_FILE_PATH}

  frontend:
    build:
      context: ./frontend/ai-voice--app
    ports:
      - "80:80"
    command: [ "npm", "run", "preview", "--", "--host", "0.0.0.0" ]
    restart: always
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - VITE_BASE_API_URL=${VITE_BASE_API_URL}
    depends_on:
      - backend
